"""
99 - Results compendium
=======================
Collects every table and figure produced by scripts 00-16 into
  outputs/PREX-Edu_all_tables.xlsx     (one formatted sheet per table + index)
  outputs/PREX-Edu_results_compendium.docx  (captions, tables, figures - ready
                                              to copy into the manuscript)
"""
from _common import C, get_logger

import json
import re

import pandas as pd
from docx import Document
from docx.enum.section import WD_ORIENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Cm, Pt, RGBColor
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

log = get_logger("99_compendium")
reg = json.loads((C.TAB_DIR / "_registry.json").read_text())


def sort_key(name):
    order = {"T": 0, "F": 1, "P": 2, "S": 3, "A": 4}
    m = re.match(r"([A-Za-z]+)(\d+)", name)
    return (order.get(name[0], 9), int(m.group(2)) if m else 0, name)


tables = sorted([n for n in reg if (C.TAB_DIR / f"{n}.csv").exists()], key=sort_key)
figs = sorted([p.stem for p in C.FIG_DIR.glob("*.png")], key=lambda s: (
    {"Fig0": 0, "Fig1": 0, "FigP": 1, "FigS": 2, "FigA": 3}.get(s[:4], 9), s))

# ---------------- Excel ----------------------------------------------------- #
xl = C.OUT / "PREX-Edu_all_tables.xlsx"
thin = Side(style="thin", color="D1D5DB")
with pd.ExcelWriter(xl, engine="openpyxl") as w:
    idx = pd.DataFrame([{"Sheet": n[:31], "Caption": reg[n]["caption"], "Note": reg[n].get("note", "")} for n in tables])
    idx.to_excel(w, sheet_name="INDEX", index=False)
    for n in tables:
        df = pd.read_csv(C.TAB_DIR / f"{n}.csv")
        df.to_excel(w, sheet_name=n[:31], index=False, startrow=2)
        ws = w.sheets[n[:31]]
        ws["A1"] = reg[n]["caption"]
        ws["A1"].font = Font(bold=True, size=11)
        if reg[n].get("note"):
            ws.cell(row=len(df) + 5, column=1, value="Note. " + reg[n]["note"]).font = Font(italic=True, size=9)
        for c in range(1, df.shape[1] + 1):
            h = ws.cell(row=3, column=c)
            h.font = Font(bold=True, color="FFFFFF")
            h.fill = PatternFill("solid", fgColor="1F3A5F")
            h.alignment = Alignment(wrap_text=True, vertical="center", horizontal="center")
            width = max([len(str(h.value))] + [len(str(v)) for v in df.iloc[:, c - 1].astype(str)]) + 2
            ws.column_dimensions[get_column_letter(c)].width = min(max(width, 9), 60)
            for r in range(4, len(df) + 4):
                cell = ws.cell(row=r, column=c)
                cell.border = Border(top=thin, bottom=thin, left=thin, right=thin)
                cell.alignment = Alignment(wrap_text=True, vertical="top")
                if r % 2 == 0:
                    cell.fill = PatternFill("solid", fgColor="F3F4F6")
        ws.freeze_panes = "A4"
    wi = w.sheets["INDEX"]
    for col, wd in zip("ABC", [32, 90, 90]):
        wi.column_dimensions[col].width = wd
log.info(f"Excel -> {xl}")

# ---------------- Word ------------------------------------------------------ #
doc = Document()
st = doc.styles["Normal"]
st.font.name = "Times New Roman"
st.font.size = Pt(10)
sec = doc.sections[0]
sec.orientation = WD_ORIENT.LANDSCAPE
sec.page_width, sec.page_height = sec.page_height, sec.page_width
for side in ("left_margin", "right_margin", "top_margin", "bottom_margin"):
    setattr(sec, side, Cm(1.8))
doc.add_heading("PREX-Edu — Results compendium", 0)
doc.add_paragraph("Auto-generated by scripts/99_build_compendium.py. Every number below is produced by the code in "
                  "this repository from data/raw/student_performance_dataset.xlsx. Prefixes: T/Fig = main manuscript; "
                  "P/FigP = primary nested-CV evaluation (recommended to replace Tables 6–9 / Figure 3); "
                  "S/FigS = supplementary; A/FigA = appendix.")
if C.FAST:
    doc.add_paragraph("WARNING: generated in FAST mode - numbers are NOT reportable.").runs[0].font.color.rgb = RGBColor(200, 0, 0)

doc.add_heading("Figures", 1)
for f in figs:
    doc.add_paragraph(f).runs[0].bold = True
    doc.add_picture(str(C.FIG_DIR / f"{f}.png"), width=Cm(22) if not f.startswith("Fig01") else Cm(25))
    doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER

doc.add_heading("Tables", 1)
for n in tables:
    df = pd.read_csv(C.TAB_DIR / f"{n}.csv").fillna("")
    p = doc.add_paragraph()
    r1 = p.add_run(f"{n}. ")
    r1.bold = True
    p.add_run(reg[n]["caption"]).italic = True
    ncol = df.shape[1]
    fs = Pt(8 if ncol <= 8 else 7 if ncol <= 12 else 6)
    t = doc.add_table(rows=1, cols=ncol)
    t.style = "Light Grid Accent 1"
    for j, c in enumerate(df.columns):
        cell = t.rows[0].cells[j]
        cell.text = str(c)
        for run in cell.paragraphs[0].runs:
            run.font.size = fs
            run.bold = True
    for _, row in df.head(80).iterrows():
        cells = t.add_row().cells
        for j, v in enumerate(row.values):
            cells[j].text = str(v)
            for run in cells[j].paragraphs[0].runs:
                run.font.size = fs
    if len(df) > 80:
        doc.add_paragraph(f"(first 80 of {len(df)} rows shown — full table in {n}.csv)").runs[0].font.size = Pt(8)
    if reg[n].get("note"):
        q = doc.add_paragraph()
        rr = q.add_run("Note. " + reg[n]["note"])
        rr.font.size = Pt(8)
        rr.italic = True
    doc.add_paragraph()
out = C.OUT / "PREX-Edu_results_compendium.docx"
doc.save(out)
log.info(f"Word -> {out}")
